jboss-container-images/jboss-eap-modules

- jboss-eap-cd-openshift-launch/added/launch/messaging.sh
https://issues.jboss.org/browse/CLOUD-2652
Signed-Off-By: Ken Wills <kwills@redhat.com>
> CLOUD-2652 fix queue / topic seperator

- jboss-eap-cd-base-installer/module.yaml
https://issues.jboss.org/browse/CLOUD-2555
> [CLOUD-2555] - update to CR2

- jboss-eap-cd-base-installer/README.txt
https://issues.jboss.org/browse/CLOUD-2717
> CLOUD-2717 Change artifact / installer from external repo to be local to jboss-eap-7-image

- jboss-eap-cd-jolokia/added/standalone.conf
https://issues.jboss.org/browse/CLOUD-2797
> [CLOUD-2797] - update jolokia config to support both old and new JSON modules

- jboss-eap-cd-openshift-launch/configure.sh
- jboss-eap-cd14-openshift/added/standalone-openshift.xml
- jboss-eap-cd14-openshift/configure.sh
- jboss-eap-cd14-openshift/module.yaml
https://issues.jboss.org/browse/CLOUD-2730
This one of 3 changes related to this JIRA:
1) https://github.com/jboss-container-images/jboss-eap-7-image/pull/93 to get the needed bits in the standalone image
2) This, to add the extension/subsystem to our config
3) https://github.com/jboss-openshift/cct_module/pull/280 to use the subsystem in our probes if available
> [CLOUD-2730] Add the MicroProfile Health Check extension

- jboss-eap-cd-openshift-launch/added/launch/openshift-common.sh
- jboss-eap-cd14-openshift/added/standalone-openshift.xml
- jboss-eap-config-tracing/added/launch/tracing.sh
- jboss-eap-config-tracing/configure.sh
- jboss-eap-config-tracing/module.yaml
Signed-off-by: Brian Stansberry <brian.stansberry@redhat.com>
https://issues.jboss.org/browse/CLOUD-2728
> [CLOUD-2728] Integrate Microprofile OpenTracing

- jboss-eap-config-jgroups/added/launch/ha.sh
- jboss-eap-config-jgroups/module.yaml
- jboss-eap-config-jgroups/test/ha.bats
https://issues.jboss.org/browse/CLOUD-2788
https://issues.jboss.org/browse/CLOUD-2546
> [CLOUD-2788 / CLOUD-2546] - support for upstream KUBE_PING and DNS_PING

- tests/features/7/7.2/basic.feature
> Correct EAP 7.2 behave tests label

- jboss-eap-cd14-openshift/added/standalone-openshift.xml
- jboss-eap-config-jgroups/added/launch/ha.sh
- jboss-eap-config-jgroups/module.yaml
- jboss-eap-config-jgroups/test/ha.bats
- jboss-eap72-openshift/added/standalone-openshift.xml
https://issues.jboss.org/browse/CLOUD-3016
https://issues.jboss.org/browse/CLOUD-2996
> [CLOUD-3016] - updates for jgroups config & updated upstream DNS_PING

- jboss-eap-cd-openshift-launch/added/launch/messaging.sh
- jboss-eap-cd-openshift-launch/test/messaging.bats
* Removing the default JMS factory
Jira: https://issues.jboss.org/browse/CLOUD-3036
> [CLOUD-3036] Removing the default JMS factory

- .gitignore
- jboss-eap-cd-openshift-modules/added/modules/system/layers/openshift/io/narayana/openshift-recovery/main/module.xml
- jboss-eap-cd-openshift-modules/configure.sh
- jboss-eap-cd-openshift-modules/module.yaml
https://issues.jboss.org/browse/CLOUD-2542
adding transaction recovery related artifacts for being available in `eap-cd` branch
> [CLOUD-2542] adding module which links jar files needed for storing txn marker in jdbc

- os-eap-activemq-rar/module.yaml
https://issues.jboss.org/browse/CLOUD-2923
> CLOUD-2923 - increment activemq module version to make distinct from legacy cct_module version

- jboss-eap-cd-openshift-launch/added/launch/activemq-subsystem.xml
- jboss-eap-cd-openshift-launch/test/standalone-openshift-configure-mq.xml
- jboss-eap-cd14-openshift/added/standalone-openshift.xml
- jboss-eap-cd15-openshift/added/standalone-openshift.xml
- jboss-eap72-openshift/added/standalone-openshift.xml
- os-eap-launch/added/launch/datasource-common.sh
- os-eap7-launch/added/launch/activemq-subsystem.xml
- os-eap71-openshift/added/standalone-openshift.xml
https://issues.jboss.org/browse/CLOUD-2784
> [CLOUD-2784] - provide expressions to enable undertow and activemq statistics

- os-eap-launch/added/launch/datasource-common.sh
https://issues.jboss.org/browse/CLOUD-3066
Signed-off-by: Ken Wills
> [CLOUD-3066] - add additional statistics for datasources, correct typo in quotes

- jboss-eap-cd15-openshift/added/standalone-openshift.xml
- update CD15 openshift configs for CR1
https://issues.jboss.org/browse/CLOUD-3071
> [CLOUD-3071] Create an EAP CD 15 openshift image

- jboss-eap-cd-openshift-launch/added/launch/openshift-common.sh
- jboss-eap-cd14-openshift/added/standalone-openshift.xml
- jboss-eap-cd15-openshift/added/standalone-openshift.xml
- jboss-eap72-openshift/added/standalone-openshift.xml
- os-eap7-launch/added/launch/configure_logger_category.sh
- os-eap7-launch/added/launch/openshift-common.sh
- os-eap7-launch/tests/bats/logging/configure-logging-category.bats
- os-eap70-openshift/added/standalone-openshift.xml
- os-eap71-openshift/added/standalone-openshift.xml
https://issues.jboss.org/browse/CLOUD-3102
> [CLOUD-3102] - Allow configuration of logger category

- os-eap-txnrecovery/bash/added/partitionPV.sh
https://issues.jboss.org/browse/CLOUD-3082
Data consistency issue can be caused by the fact when the recovery marker SQL storage is not available the marker is not created and thus it can't block from cleaning.
This fix does not permit starting the EAP app server until the SQL storage is available.
> [CLOUD-3082] verify insertion of txn recovery marker succeed or not proceed

- os-eap-launch/test/datasource.bats
- os-eap7-launch/added/launch/tx-datasource.sh
- os-eap7-launch/tests/bats/datasource/common.bash
- os-eap7-launch/tests/bats/datasource/configure.bats
- os-eap7-launch/tests/bats/datasource/expectations/datasources_ibmdb2_xa.xml
- os-eap7-launch/tests/bats/datasource/expectations/datasources_mysql_nonxa.xml
- os-eap7-launch/tests/bats/datasource/expectations/datasources_other_nonxa.xml
- os-eap7-launch/tests/bats/datasource/expectations/datasources_other_xa.xml
- os-eap7-launch/tests/bats/datasource/expectations/datasources_postgresql_nonxa.xml
- os-eap7-launch/tests/bats/datasource/expectations/datasources_postgresql_nourl_xa.xml
- os-eap7-launch/tests/bats/datasource/expectations/datasources_sybase_pool_nonxa.xml
- os-eap7-launch/tests/bats/datasource/expectations/datasources_sybase_validation_nonxa.xml
- os-eap7-launch/tests/bats/datasource/expectations/prefix_ibmdb2_xa.xml
- os-eap7-launch/tests/bats/datasource/expectations/prefix_mysql_xa.xml
- os-eap7-launch/tests/bats/datasource/expectations/prefix_oracle_xa.xml
- os-eap7-launch/tests/bats/datasource/expectations/prefix_postgresql_nonxa.xml
- os-eap7-launch/tests/bats/datasource/expectations/prefix_postgresql_xa.xml
- os-eap7-launch/tests/bats/launch-common/launch-common.bats
- os-eap7-launch/tests/bats/logging/configure-logging-category.bats
- run-all-tests.sh
- test-common/log_utils.bash
- test-common/openshift-node-name.sh
- test-common/xml_utils.bash
> Fix some includes for bats tests add script to run all tests that have a .bats extension for CI

- jboss-eap-cd-jolokia/added/standalone.conf
- jboss-eap-logging-jdk11/added/module.xml
- jboss-eap-logging-jdk11/configure.sh
- jboss-eap-logging-jdk11/module.yaml
- jboss-eap72-openshift/72-openjdk11/added/standalone-openshift.xml
- jboss-eap72-openshift/72-openjdk11/configure.sh
- jboss-eap72-openshift/72-openjdk11/module.yaml
- os-eap-datasource/1.0/added/launch/datasource-common.sh
- os-eap-datasource/1.0/configure.sh
- os-eap-datasource/1.0/module.yaml
- os-eap-datasource/1.0/test/datasource.bats
- os-eap-hawkular/added/standalone.conf
- os-eap-launch/added/launch/datasource-common.sh
- os-eap-txnrecovery/bash/added/partitionPV.sh
- os-eap7-launch/tests/bats/datasource/configure.bats
- tests/features/7/7.2/basic.feature
- tests/features/7/basic.feature
- tests/features/7/datasource.feature
- tests/features/7/hawkular.feature
- tests/features/7/messaging.feature
- tests/features/7/s2i.feature
- tests/features/7/sso.feature
- tests/features/common.feature
https://issues.jboss.org/browse/CLOUD-3121
> CLOUD-3121 - EAP 7.2 / OpenJDK 11 image support

- jboss-eap-cd16-openshift/added/standalone-openshift.xml
https://issues.jboss.org/browse/CLOUD-3185
Signed-off-by: Brian Stansberry <brian.stansberry@redhat.com>
> [CLOUD-3185] Put the entire xml element on a single line

- os-eap-txnrecovery/bash/added/partitionPV.sh
https://issues.jboss.org/browse/CLOUD-3178
> CLOUD-3178 - Update partitionPV to allow more behave tests to run

- jboss-eap-cd-openshift-modules/module.yaml
- os-eap-db-drivers/module.yaml
- os-eap-launch/module.yaml
- os-eap-probes/module.yaml
- os-eap-txnrecovery/module.yaml
- os-eap64-modules/module.yaml
- os-eap64-ping/module.yaml
- os-eap7-ping/module.yaml
- os-eap70-sso/module.yaml
- os-eap71-modules/module.yaml
https://issues.jboss.org/browse/CLOUD-3175
> CLOUD-3175 - Update builds to not use cacher (#58) [7.2.x]

- os-eap64-ping/configure.sh
- os-eap64-ping/module.yaml
- os-eap7-ping/configure.sh
- os-eap7-ping/module.yaml
See:
https://issues.jboss.org/browse/CLOUD-3163
> [CLOUD-3163] - Update openshift-ping version

- os-eap64-ping/configure.sh
- os-eap64-ping/module.yaml
- os-eap7-ping/configure.sh
- os-eap7-ping/module.yaml
https://issues.jboss.org/browse/CLOUD-3192
> [CLOUD-3192] Update openshift-ping version

- os-eap64-ping/configure.sh
- os-eap64-ping/module.yaml
- os-eap7-ping/configure.sh
- os-eap7-ping/module.yaml
https://issues.jboss.org/browse/CLOUD-3191
> [CLOUD-3191] Update openshift-ping version

- os-eap-sso/added/keycloak.sh
See: https://issues.jboss.org/browse/CLOUD-3214
> [CLOUD-3214] - Fixing script compatiility with python3

- os-eap-db-drivers/configure.sh
- os-eap-db-drivers/module.yaml
https://issues.jboss.org/browse/CLOUD-3211
> [CLOUD-3211] update mongodb driver to mongodb36

- os-eap-db-drivers/configure.sh
- os-eap-db-drivers/module.yaml
https://issues.jboss.org/browse/CLOUD-3223
> [CLOUD-3223] update mongodb driver to mongodb36

- os-eap64-sso/configure.sh
- os-eap64-sso/module.yaml
- os-eap70-sso/configure.sh
- os-eap70-sso/module.yaml
https://issues.jboss.org/browse/CLOUD-3180
> CLOUD-3180 - update EAP SSO Adapters to RH-SSO 7.3

- os-eap7-launch/tests/bats/logging/configure-logging-category.bats
https://issues.jboss.org/browse/CLOUD-3233
> CLOUD-3233 - fix logging tests

- os-eap-sso/added/keycloak.sh
- os-eap-sso/tests/bats/README.md
- os-eap-sso/tests/bats/common.bash
- os-eap-sso/tests/bats/hostname-discovery.bats
- os-eap-sso/tests/bats/mock_responses/multi-route.json
- os-eap-sso/tests/bats/mock_responses/no-route.json
- os-eap-sso/tests/bats/mock_responses/single-route.json
- os-eap-sso/tests/bats/server/README.md
- os-eap-sso/tests/bats/server/shinatra.sh
https://issues.jboss.org/browse/CLOUD-3204
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/87
> CLOUD-3204 [7.2.x] Discover application routes during Keycloak client configuration via Kubernetes API

- os-eap-launch/test/datasource.bats
- os-eap7-launch/added/launch/tx-datasource.sh
- os-eap7-launch/tests/bats/datasource/common.bash
- os-eap7-launch/tests/bats/datasource/configure.bats
- os-eap7-launch/tests/bats/datasource/expectations/datasources_ibmdb2_xa.xml
- os-eap7-launch/tests/bats/datasource/expectations/datasources_mysql_nonxa.xml
- os-eap7-launch/tests/bats/datasource/expectations/datasources_other_nonxa.xml
- os-eap7-launch/tests/bats/datasource/expectations/datasources_other_xa.xml
- os-eap7-launch/tests/bats/datasource/expectations/datasources_postgresql_nonxa.xml
- os-eap7-launch/tests/bats/datasource/expectations/datasources_postgresql_nourl_xa.xml
- os-eap7-launch/tests/bats/datasource/expectations/datasources_sybase_pool_nonxa.xml
- os-eap7-launch/tests/bats/datasource/expectations/datasources_sybase_validation_nonxa.xml
- os-eap7-launch/tests/bats/datasource/expectations/prefix_ibmdb2_xa.xml
- os-eap7-launch/tests/bats/datasource/expectations/prefix_mysql_xa.xml
- os-eap7-launch/tests/bats/datasource/expectations/prefix_oracle_xa.xml
- os-eap7-launch/tests/bats/datasource/expectations/prefix_postgresql_nonxa.xml
- os-eap7-launch/tests/bats/datasource/expectations/prefix_postgresql_xa.xml
- os-eap7-launch/tests/bats/launch-common/launch-common.bats
- os-eap7-launch/tests/bats/logging/configure-logging-category.bats
- run-all-tests.sh
- test-common/log_utils.bash
- test-common/openshift-node-name.sh
- test-common/xml_utils.bash
https://issues.jboss.org/browse/CLOUD-3212
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/67
> [7.2.x] [CLOUD-3212] Update bats tests to run with new CI

- os-eap-db-drivers/configure.sh
- os-eap-db-drivers/module.yaml
https://issues.jboss.org/browse/CLOUD-3218
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/100
> [CLOUD-3218] update mongodb driver to mongodb36

- os-eap64-sso/configure.sh
- os-eap64-sso/module.yaml
- os-eap70-sso/configure.sh
- os-eap70-sso/module.yaml
https://issues.jboss.org/browse/CLOUD-3216
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/85
> [CLOUD-3216] update EAP SSO Adapters to RH-SSO 7.3.1

- os-eap64-sso/configure.sh
- os-eap64-sso/module.yaml
- os-eap70-sso/configure.sh
- os-eap70-sso/module.yaml
https://issues.jboss.org/browse/CLOUD-3220
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/85
> [CLOUD-3220] update EAP SSO Adapters to RH-SSO 7.3.1

- os-eap-datasource/1.0/added/launch/datasource-common.sh
- os-eap-launch/added/launch/datasource-common.sh
https://issues.jboss.org/browse/CLOUD-3231
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/96
> [7.2.x-openjdk11] [CLOUD-3209] SSO_SECRET parameter should be required if configuring RH-SSO integration

- jboss-eap-config-openshift/CD17.0/added/standalone-openshift.xml
https://issues.jboss.org/browse/CLOUD-3319
> CLOUD-3319 - remove mysql & postgres from CD 17 standalone-openshift.xml

- jboss-eap72-openshift/added/standalone-openshift.xml
- os-eap7-launch/added/launch/configure_logger_category.sh
- os-eap7-launch/tests/bats/logging/configure-logging-category.bats
https://issues.jboss.org/browse/CLOUD-3320
> [CLOUD-3320] - Missing LOGGER-CATEGORY in config breaks tests

- os-eap-migration/added/launch/openshift-migrate-common.sh
https://issues.jboss.org/browse/CLOUD-3325
> [CLOUD-3325] - openshift-migrate.sh terminates with Max retries exceeded with url: /management

- os-eap-txnrecovery/bash/added/partitionPV.sh
https://issues.jboss.org/browse/CLOUD-3328
> [CLOUD-3328] verify insertion of txn recovery marker succeed otherwise do not proceed

- jboss-eap-cd-base-installer/module.yaml
- jboss-eap-config-openshift/EAP7.3.0.Beta/added/standalone-openshift.xml
- jboss-eap-config-openshift/EAP7.3.0.Beta/configure.sh
- jboss-eap-config-openshift/EAP7.3.0.Beta/module.yaml
- os-eap-launch/added/launch/datasource-common.sh
https://issues.jboss.org/browse/CLOUD-3331
> [CLOUD-3331] - OpenShift Images for 7.3 Beta

- os-eap-migration/added/launch/openshift-migrate-common.sh
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/125
https://issues.jboss.org/browse/CLOUD-3332
https://issues.jboss.org/browse/CLOUD-3347
> [CLOUD-3332] - openshift-migrate.sh terminates with Max retries exceeded with url: /management

- jboss-eap-cd-base-installer/module.yaml
https://issues.jboss.org/browse/CLOUD-3337
> [CLOUD-3337] - CeKit 3.3.1 requires version in module.xml

- jboss-eap-cd-jolokia/added/standalone.conf
https://issues.jboss.org/browse/CLOUD-3398
This is a manual merge of https://github.com/wildfly/wildfly-cekit-modules/commit/0fecc392ea5bce7f5f9b66875f49636e68eee7e5
> CLOUD-3398 - update jolokia config for new jakarta jar locations

- jboss/container/eap/galleon/build-settings/osbs/artifacts/settings.xml
- jboss/container/eap/galleon/build-settings/osbs/configure.sh
- jboss/container/eap/galleon/build-settings/osbs/module.yaml
- jboss/container/eap/galleon/build-settings/public/module.yaml
https://issues.jboss.org/browse/CLOUD-3408
New module to set proper settings at image build time.
> Fix for CLOUD-3408, Allow to build image in osbs

- jboss/container/eap/cd/latest/module.yaml
https://issues.jboss.org/browse/CLOUD-3400
Update to latest version.
> Adjust to latest version

- jboss/container/eap/cd/latest/module.yaml
> Update to EAP CD18 CR1

- jboss-eap-cd-jolokia/added/standalone.conf
Jira issue: https://issues.jboss.org/browse/CLOUD-3443
> [CLOUD-3443] Remove invalid characters in jboss-eap-cd-jolokia/added/standalone.conf

- jboss-eap72-openshift/added/standalone-openshift.xml
https://issues.jboss.org/browse/CLOUD-3433
Signed-off-by: Daniel Kreling <dkreling@gmail.com>
> [CLOUD-3433] fix version of io:subsystem in standalone-openshift.xml

- tests/features/driver.feature
- tests/features/galleon.feature
- tests/features/logging.feature
- tests/features/tracing.feature
https://issues.jboss.org/browse/CLOUD-3454
> Fix for CLOUD-3454, 7.3 image, added tests annotations

- os-eap-hawkular/added/standalone.conf
https://issues.redhat.com/browse/CLOUD-3402
> CLOUD-3402 Remove deprecated hawkular agent jar and related scripting

- jboss/container/eap/galleon/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/configs/standalone/standalone.xml/config.xml
- jboss/container/eap/galleon/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/feature_groups/os-observability.xml
Issue: https://issues.redhat.com/browse/CLOUD-3425
Issue: https://issues.redhat.com/browse/CLOUD-3426
Changes to fix default config.
> Default configuration changes for 7.3

- os-eap-migration/added/launch/openshift-migrate-common.sh
- os-eap-txnrecovery/bash/added/partitionPV.sh
Reverts jboss-container-images/jboss-eap-modules#172
> Revert "Fix for CLOUD-3471, Can't run multiple server during migration"

- jboss/container/eap/galleon/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/layers/standalone/application-security-realm/layer-spec.xml
- jboss/container/eap/galleon/config/mp/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/configs/standalone/standalone-microprofile-ha.xml/config.xml
Issue: https://issues.redhat.com/browse/CLOUD-3565
Issue: https://issues.redhat.com/browse/CLOUD-3566
> Fix for CLOUD-3565, CLOUD-3566

- jboss/container/eap/galleon/config/mp/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/configs/standalone/model.xml
Issue: https://issues.redhat.com/browse/CLOUD-3568
> Fix for CLOUD-3568, statefulset launch script not provisioned in XP 1.0

- jboss-eap-config-openshift/EAP7.3.0/added/standalone-openshift.xml
- jboss-eap-config-openshift/EAP7.3.0/configure.sh
- jboss-eap-config-openshift/EAP7.3.0/module.yaml
https://issues.redhat.com/browse/CLOUD-3606
> [CLOUD-3606] - Legacy EAP 7.3 standalone configuration for OpenShift

- os-eap-migration/added/launch/openshift-migrate-common.sh
- os-eap-txnrecovery/bash/added/partitionPV.sh
- os-eap-txnrecovery/bash/added/queryosapi.py
- os-eap-txnrecovery/bash/test/common.bash
- os-eap-txnrecovery/bash/test/partitionPV.bats
- os-eap-txnrecovery/bash/test/test_queryosapi.py
- os-eap-txnrecovery/run/python3/osquery.py
plus do not show whole exception stacktrace when debug is not switch on
https://issues.redhat.com/browse/CLOUD-3517
> [CLOUD-3517] correct processing of command exit status when OpenShift API is not available

- .github/workflows/main.yml
https://issues.redhat.com/browse/CLOUD-3626
> CLOUD-3626 - enable GH actions for jboss-eap-modules

- jboss/container/config/cd/19.0/standalone-openshift.xml
- jboss/container/eap/galleon/config/ee/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/configs/standalone/standalone.xml/config.xml
Resolves
https://issues.redhat.com/browse/CLOUD-3506
> CLOUD-3506 Remove mod_cluster from OpenShift default configuration

- jboss/container/config/cd/19.0/standalone-openshift.xml
- jboss/container/eap/galleon/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/pom.xml
- jboss/container/eap/galleon/config/ee/artifacts/opt/jboss/container/eap/galleon/definitions/fat-default-server/provisioning.xml
- jboss/container/eap/galleon/config/ee/artifacts/opt/jboss/container/eap/galleon/definitions/slim-default-server/provisioning.xml
- jboss/container/eap/galleon/module.yaml
- os-eap-txnrecovery/bash/test/test_queryosapi.py
https://issues.redhat.com/browse/CLOUD-3670
> CLOUD-3670 - EAP CD 20 Release

- os-eap-launch/added/launch/datasource-common.sh
- tests/features/6/datasource.feature
- tests/features/7/datasource.feature
Related jiras:
[CLOUD-2903](https://issues.jboss.org/browse/CLOUD-2903)
[RHPAM-2261](https://issues.jboss.org/browse/RHPAM-2261)
> [RHPAM-2261] - DB2 fails with externaldb template

- jboss/container/eap/prometheus/agent/src/standalone.conf
https://issues.redhat.com/browse/JBEAP-20552
> JBEAP-20552 - Fix for starting prometheus java-agent

- jboss/container/eap/galleon/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/pom.xml
- jboss/container/eap/galleon/config/ee/artifacts/opt/jboss/container/eap/galleon/definitions/fat-default-server/provisioning.xml
- jboss/container/eap/galleon/config/ee/artifacts/opt/jboss/container/eap/galleon/definitions/slim-default-server/provisioning.xml
- jboss/container/eap/galleon/module.yaml
Issue:https://issues.redhat.com/browse/CLOUD-3859
> Fix for CLOUD-3859, CD21 image contains eap-s2i-galleon-pack-20.0.0.Final.pom

- tests/features/basic.feature
- tests/features/jgroups.feature
https://issues.redhat.com/browse/CLOUD-3509
> CLOUD-3509 correct misspelling / typo of keystore

- jboss/container/eap/galleon/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/feature_groups/os-observability.xml
- jboss/container/eap/galleon/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/layers/standalone/observability/layer-spec.xml
- jboss/container/eap/galleon/config/ee/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/configs/standalone/standalone.xml/config.xml
Issue: https://issues.redhat.com/browse/CLOUD-3878
> Fix for CLOUD-3878, setting prefix of smallrye metrics is breaking image build

- tests/features/basic.feature
Includes the following Jiras:
https://issues.redhat.com/browse/CLOUD-3966
https://issues.redhat.com/browse/CLOUD-3967
https://issues.redhat.com/browse/CLOUD-3968
> [CLOUD-3966][CLOUD-3967][CLOUD-3968] Fix behave tests for 7.4.0.GA

- os-eap70-sso/configure.sh
- os-eap70-sso/module.yaml
https://issues.redhat.com/browse/CLOUD-3982
> CLOUD-3982 Update SSO adapters to latest 7.4.x versions

- tests/features/driver.feature
This was a left over from previous PR.
> [7.4] Remove test branch from feature file

- jboss/container/eap/galleon/module.yaml
https://issues.redhat.com/browse/CLOUD-4005
> CLOUD-4005 - EAP XP 3.0 - Wrong S2I_FP_VERSION

- jboss/container/eap/launch/added/launch/launch-config.sh
https://issues.redhat.com/browse/CLOUD-4009
> CLOUD-4009 - Missing mp-config.sh and tracing.sh in image

- os-eap-activemq-rar/module.yaml
[KIECLOUD-560] - Bump activemq-rar version
https://issues.redhat.com/browse/KIECLOUD-560
Signed-off-by: Achyut Madhusudan <amadhusu@redhat.com>
Thanks for submitting your Pull Request!
Please make sure your PR meets the following requirements:
> [KIECLOUD-560] - Bump activemq-rar version

- os-eap-activemq-rar/module.yaml
[KIECLOUD-560] - Bump activemq-rar version for 7.3.x
https://issues.redhat.com/browse/KIECLOUD-560
Signed-off-by: Achyut Madhusudan <amadhusu@redhat.com>
Thanks for submitting your Pull Request!
Please make sure your PR meets the following requirements:
> [KIECLOUD-560] - Bump activemq-rar version for 7.3.x

- jboss/container/eap/galleon/module.yaml
- jboss/container/eap/setup/module.yaml
https://issues.redhat.com/browse/CLOUD-4080
> CLOUD-4080 - EAP XP 4.0 Images

- jboss/container/eap/galleon/module.yaml
- jboss/container/eap/setup/module.yaml
Reverts jboss-container-images/jboss-eap-modules#259
> Revert "CLOUD-4080 - EAP XP 4.0 Images"

- tests/features/basic.feature
ParserError: Failed to parse "/data/dev/sources/rhpam-7-openshift-image/businesscentral/target/test/features/jboss-eap-modules/basic.feature": 
Parser failure in state steps, at line 97: "￼   Then container log should contain -javaagent:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties"
> fix parser issue

- os-eap70-sso/configure.sh
- os-eap70-sso/module.yaml
Issue: https://issues.redhat.com/browse/CLOUD-4147
> Bump SSO adapters to 7.6.3

- jboss/container/eap/jdk-cert-remove/configure.sh
- jboss/container/eap/jdk-cert-remove/module.yaml
- jboss/container/eap/jdk-cert/configure.sh
- jboss/container/eap/jdk-cert/module.yaml
Issue: https://issues.redhat.com/browse/CLOUD-4190
> Add modules for cert installation and removal

- jboss/container/eap/jdk-cert-remove/configure.sh
- jboss/container/eap/jdk-cert/configure.sh
Issue: https://issues.redhat.com/browse/CLOUD-4198
> Add new 2022 certificate

- jboss/container/eap/jdk-cert-remove/configure.sh
- jboss/container/eap/jdk-cert/configure.sh
The previous certificate was removed now we are using the new one
> [EAPPROD-895] Update certificate

- os-eap-activemq-rar/module.yaml
Issue: https://issues.redhat.com/browse/EAPPROD-1056
> [EAPPROD-1056] Update os-eap-activemq-rar artifact to have source
