- jboss-eap-cd-openshift-launch/added/standalone-openshift.xml
<groups transport: <property name="use_ip_addrs">true</property>
> [JBEAP-14477] workaround for no physical address for foo, dropping message warnings

- jboss-eap-cd-openshift-launch/added/standalone-openshift.xml
This is a follow up to JBEAP-14477, which should have really been CLOUD-2425
> CLOUD-2425 - fix WS

- jboss-eap-cd-openshift-launch/added/standalone-openshift.xml
This is the EAP CD variant of https://issues.jboss.org/browse/CLOUD-1945 which didn't get merged at the time. This change is needed for the embedded broker removal change.
> CLOUD-1945 - EAP CD merge

- jboss-eap-cd-openshift-launch/added/standalone-openshift.xml
Since we reverted the embedded broker removal, the socket-bindings shuffled a bit here: https://github.com/jboss-openshift/cct_module/pull/218
This updates the EAP CD standalone-openshift.xml to match.
> CLOUD-2282 [EAP CD] - match the socket bindings used for JMS etc in eap71

- jboss-eap-cd-logging/added/launch/json_logging.sh
- jboss-eap-cd-logging/configure.sh
- jboss-eap-logging-ext/added/launch/json_logging.sh
- jboss-eap-logging-ext/added/logging.properties
- jboss-eap-logging-ext/configure.sh
- jboss-eap-logging-ext/module.yaml
https://issues.jboss.org/browse/CLOUD-2706
- Add new jboss-eap-logging-ext for configuration of JSON logging on EAP <= 7.1 and EAP 6.4
> [CLOUD-2706] update JSON logging to capture server boot

- jboss-eap-cd-openshift-launch/added/launch/openshift-common.sh
- jboss-eap-cd14-openshift/added/standalone-openshift.xml
- jboss-eap-config-mp_config/added/launch/mp-config.sh
- jboss-eap-config-mp_config/configure.sh
- jboss-eap-config-mp_config/module.yaml
- jboss-eap-config-mp_config/test/README.txt
- jboss-eap-config-mp_config/test/logging.sh
- jboss-eap-config-mp_config/test/mp-config.bats
Signed-off-by: Brian Stansberry <brian.stansberry@redhat.com>
https://issues.jboss.org/browse/CLOUD-2729
This introduces a new config script, which won't be available for all EAP7 based images, so I create a new openshift-common.sh.
This impl varies some from the discussion on CLOUD-2729 as I want to keep it simple and require the user to provide an absolute path for MICROPROFILE_CONFIG_DIR.  There's no dir like '/etc/config' available OOTB in our images. A user wanting to mount a ConfigMap for this to use is going to have to specify the absolute dir as part of that mount so they know the path and can readily declare it here.
This will require a separate PR for jboss-eap-7-openshift-image to include the new module.
@jmesnil I also added a MICROPROFILE_CONFIG_DIR_ORDINAL to allow setting …
> [CLOUD-2729] Microprofile Config integration

- jboss-eap-cd-openshift-launch/added/launch/activemq-subsystem.xml
- jboss-eap-cd14-openshift/added/standalone-openshift.xml
Note this does not include the WFLY-10541 change discussed at https://lists.jboss.org/pipermail/wildfly-dev/2018-July/006601.html. That change was to add an expression to the standard WildFly configs to allow the id to be set easily via the command line. The standalone-openshift.xml already supports this with a value of ${jboss.node.name} which will be unique per pod. Changing that to the WFLY-10541 default of ${jboss.tx.node.id:1} will break things as jboss.tx.node.id will not be set and '1' is not an appropriate value.
It also does not include the WFLY-10614 change, which, if confirmed appropriate, will be brought in separately.
Signed-off-by: Brian Stansberry <brian.stansberry@redhat.com>
https://issues.jboss.org/browse/CLOUD-2894
> [CLOUD-2894] Port simple WF 14 changes to standalone-openshift.xml

- tests/features/7/basic.feature
to run also for RH-SSO 7.3 TP CD and RH-SSO 7.3.0.ER1 images
Also update the warning message for some JGroups tests to the form expected
by the `jboss-eap-config-jgroups` module, namely:
* https://github.com/jboss-container-images/jboss-eap-modules/blob/master/jboss-eap-config-jgroups/added/launch/jgroups.sh#L145 and
* https://github.com/jboss-container-images/jboss-eap-modules/blob/master/jboss-eap-config-jgroups/added/launch/jgroups.sh#L152
and enable these tests too (drop the @ignore label to enable them for EAP CD,
EAP 7.2.0, RH-SSO 7.3 TP CD & RH-SSO 7.3.0.ER1 images
Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>
> [CLOUD-3025] Allow selected EAP CD 14 / EAP 7.2.0.CR1 tests with updated JGroups

- os-eap-activemq-rar/module.yaml
https://issues.jboss.org/browse/CLOUD-2923
> CLOUD-2923 - upgrade activemq-rar to Rollup 10 patch

- os-eap-activemq-rar/configure.sh
- os-eap-activemq-rar/module.yaml
Signed-off-by: Ken WIlls <kwills@redhat.com>
> Update CR5 modules to include missing activemq RA configure script and increment module version to 1.1 to avoid clash with legacy cct_module version

- jboss-eap-cd-openshift-modules/module.yaml
- os-eap-db-drivers/module.yaml
- os-eap-launch/module.yaml
- os-eap-probes/module.yaml
- os-eap-txnrecovery/module.yaml
- os-eap64-modules/module.yaml
- os-eap64-ping/module.yaml
- os-eap7-ping/module.yaml
- os-eap70-sso/module.yaml
- os-eap71-modules/module.yaml
https://issues.jboss.org/browse/CLOUD-3091
> CLOUD-3091 - Update builds to not use cacher

- tests/features/6/basic.feature
- tests/features/7/basic.feature
- tests/features/7/jgroups.feature
in selected JGroups CTF tests (where appropriate)
Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>
P.S. See the result of PR change testing in the next comment
> [CLOUD-3138] Replace 'OPENSHIFT_KUBE_PING_NAMESPACE' with 'JGROUPS_PING_PROTOCOL'

- jboss-eap-cd16-openshift/added/standalone-openshift.xml
- jboss-eap-cd16-openshift/configure.sh
- jboss-eap-cd16-openshift/module.yaml
Copy standalone-openshift.xml from jboss.eap.cd15.openshift and update
it based on the standalone-full-ha.xml from WildFly 16.0.0.Final
In addition to the extensions version bumps, the only change is the
statistics-enabled attribute that uses expressions for the ejb3 and
webservices subsystems.
JIRA: https://issues.jboss.org/browse/CLOUD-3097
> [CLOUD-3097] Add jboss.eap.cd16.openshift module

- os-eap-txnrecovery/bash/added/partitionPV.sh
https://issues.jboss.org/browse/CLOUD-3135
> CLOUD-3135 - allow behave tests to override node name

- jboss-eap-config-jgroups/added/launch/ha.sh
Use `labelSelector` instead of `labels` to query the pods with the
required labels (as documented in
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#list-and-watch-filtering)
JIRA: https://issues.jboss.org/browse/CLOUD-3164
> [CLOUD-3164] URL to check view pods permission is not correct

- jboss-eap-config-jgroups/added/launch/ha.sh
- jboss-eap-config-jgroups/module.yaml
- jboss-eap-config-jgroups/test/ha.bats
https://issues.jboss.org/browse/CLOUD-3176
> [CLOUD-3176] drop deprecated openshift.KUBERNETES_PING and openshift.DNS_PING in favor of upstream implementations

- os-eap-sso/added/keycloak.sh
Please see:
https://issues.jboss.org/browse/CLOUD-3199
> [CLOUD-3199] - added warn message in case of SSO_SECRET is empty

- os-eap-sso/added/keycloak.sh
- os-eap-sso/tests/bats/README.md
- os-eap-sso/tests/bats/common.bash
- os-eap-sso/tests/bats/hostname-discovery.bats
- os-eap-sso/tests/bats/mock_responses/multi-route.json
- os-eap-sso/tests/bats/mock_responses/no-route.json
- os-eap-sso/tests/bats/mock_responses/single-route.json
- os-eap-sso/tests/bats/server/README.md
- os-eap-sso/tests/bats/server/shinatra.sh
@luck3y  this is the PR to fix https://issues.jboss.org/browse/CLOUD-3200. 
Tested with Business Central (RHPAM) images and I was able to create a keycloak client configuration with URLs from the application routes where the pod is running. 
The logic between this "discover" is to use the pod hostname. If a route is found with this name, we set the `APPLICATION_ROUTES` to it, then the script does the rest of the job and registers the keycloak client with the correct URLs.
Most of the time, templates create routes, services, pods, secrets with the same base name. So, if the template does not set the `HOSTNAME_HTTP` env variable, we try to found a URL based on this base name.
For this to work, I borrowed these functions from our code base …
> [CLOUD-3200] - querying k8s api to discover generated routes

- os-eap64-ping/configure.sh
- os-eap64-ping/module.yaml
- os-eap7-ping/configure.sh
- os-eap7-ping/module.yaml
https://issues.jboss.org/browse/CLOUD-3210
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/80
> [CLOUD-3210] 7.2.x-openjdk11] Update ping modules to 1.2.5

- os-eap-datasource/1.0/added/launch/datasource-common.sh
- os-eap-launch/added/launch/datasource-common.sh
https://issues.jboss.org/browse/CLOUD-3198
This Pull Request fixes the ampersand in URL parsing problem. the problem might be reproduced by using `DB_URL=jdbc:postgresql://172.17.0.2:5432/rhsso&ssl=true`. Without this Pull Request, the connection url would be trimmed to `jdbc:postgresql://172.17.0.2:5432/rhsso` (without `&ssl=true`). 
Dear EAP Team - I'm not sure where would you like to test this feature out. Perhaps it would be best if you could add one commit on top of mine, and implement proper test (in any place you'd like it to be).
@iankko @luck3y  Please take a look at this PR once you have a chance.
> CLOUD-3198 Datasource generation should escape ampersand

- os-eap64-ping/module.yaml
- os-eap7-ping/module.yaml
See:
https://issues.jboss.org/browse/CLOUD-3235
> [CLOUD-3235] - Update ping modules to fix certificate issue in OCP 4.1

- os-eap64-ping/configure.sh
- os-eap7-ping/configure.sh
Should be reopened:
https://issues.jboss.org/browse/CLOUD-3235
There's a VERSION var that should be updated as well. The images builds are broken because of this.
> [CLOUD-3235] - Fixing missed VERSION variable value

- os-eap-sso/added/keycloak.sh
https://issues.jboss.org/browse/CLOUD-3209
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/86
Signed-off-by: Ken Wills
> [7.2.x-openjdk11] [CLOUD-3209] SSO_SECRET parameter should be required if configuring RH-SSO integration

- os-eap-sso/added/keycloak.sh
https://issues.jboss.org/browse/CLOUD-3208
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/86
> [CLOUD-3208] - [7.2.x] SSO_SECRET parameter should be required if configuring RH-SSO integration

- os-eap64-ping/configure.sh
- os-eap64-ping/module.yaml
- os-eap7-ping/configure.sh
- os-eap7-ping/module.yaml
https://issues.jboss.org/browse/CLOUD-3237
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/103/ https://github.com/jboss-container-images/jboss-eap-modules/pull/105
> [CLOUD-3237] Update ping modules to fix certificate issue in OCP 4.1

- os-eap64-ping/configure.sh
- os-eap64-ping/module.yaml
- os-eap7-ping/configure.sh
- os-eap7-ping/module.yaml
https://issues.jboss.org/browse/CLOUD-3236
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/103/ https://github.com/jboss-container-images/jboss-eap-modules/pull/105
> [CLOUD-3236] - Update ping modules to fix certificate issue in OCP 4.1

- os-eap-launch/added/launch/datasource-common.sh
https://issues.jboss.org/browse/CLOUD-3230
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/96/
> [CLOUD-3230] Datasource generation should escape ampersand

- os-eap-sso/added/keycloak.sh
- os-eap-sso/tests/bats/README.md
- os-eap-sso/tests/bats/common.bash
- os-eap-sso/tests/bats/hostname-discovery.bats
- os-eap-sso/tests/bats/mock_responses/multi-route.json
- os-eap-sso/tests/bats/mock_responses/no-route.json
- os-eap-sso/tests/bats/mock_responses/single-route.json
- os-eap-sso/tests/bats/server/README.md
- os-eap-sso/tests/bats/server/shinatra.sh
https://issues.jboss.org/browse/CLOUD-3207
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/87
> CLOUD-3207 [7.2.x-openjdk11] Discover application routes during Keycloak client configuration via Kubernetes API

- os-eap-probes/1.0/added/livenessProbe.sh
- os-eap-probes/1.0/added/probes/probe/dmr.py
- os-eap-probes/1.0/added/probes/runner.py
- os-eap-probes/1.0/added/readinessProbe.sh
- os-eap-probes/2.0/added/livenessProbe.sh
- os-eap-probes/2.0/added/probes/probe/dmr.py
- os-eap-probes/2.0/added/probes/runner.py
- os-eap-probes/2.0/added/readinessProbe.sh
https://issues.jboss.org/browse/CLOUD-3256
> CLOUD-3256 - Allow kubernetes to control probe retries; avoid probes taking longer than kubernetes timeout settings

- jboss-eap-config-openshift/16.0-openjdk11/added/standalone-openshift.xml
- jboss-eap-config-openshift/16.0-openjdk11/configure.sh
- jboss-eap-config-openshift/16.0-openjdk11/module.yaml
- jboss-eap-config-openshift/16.0/added/standalone-openshift.xml
- jboss-eap-config-openshift/16.0/configure.sh
- jboss-eap-config-openshift/16.0/module.yaml
https://issues.jboss.org/browse/CLOUD-3122
This creates the jboss-eap-config-openshift top level module, and since we're still on EAP 16 provides configuration modules for 16.0 and 16.0-openjdk11. The only difference between them is openjdk11 has no default databases configured in standalone-openshift.xml
> [CLOUD-3122] - EAP CD - Update configs for UBI / JDK 11

- os-eap-probes/1.0/added/livenessProbe.sh
- os-eap-probes/1.0/added/readinessProbe.sh
- os-eap-probes/2.0/added/livenessProbe.sh
- os-eap-probes/2.0/added/readinessProbe.sh
https://issues.jboss.org/browse/CLOUD-2742
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/116
> [7.2.x-openjdk11] - CLOUD-2742 - Allow kubernetes to control probe retries; avoid probes taking longer than kubernetes timeout settings

- jboss-eap72-openshift/72-openjdk11/added/standalone-openshift.xml
https://issues.jboss.org/browse/CLOUD-3310
> [CLOUD-3310] Missing LOGGER-CATEGORY in openjdk11 config

- os-eap-probes/added/livenessProbe.sh
- os-eap-probes/added/probes/probe/dmr.py
- os-eap-probes/added/readinessProbe.sh
https://issues.jboss.org/browse/CLOUD-3245
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/commit/764ae61a0c8e1b90810a8bb714712ebed515c356
> CLOUD-3245 - [7.2.x] Allow kubernetes to control probe retries; avoid probes taking longer than kubernetes timeout settings

- os-eap-sso/added/keycloak.sh
- os-eap-sso/tests/bats/hostname-discovery.bats
See:
https://issues.jboss.org/browse/CLOUD-3206
https://issues.jboss.org/browse/RHPAM-1336
> [CLOUD-3206] Add default hostname ports to SSO client configuration

- os-eap-probes/added/livenessProbe.sh
- os-eap-probes/added/probe_common.sh
- os-eap-probes/added/readinessProbe.sh
https://issues.jboss.org/browse/CLOUD-3245
No upstream issue, this change is only for the 7.2.x stable branches.
> [CLOUD-3245] - [7.2.x] Allow kubernetes to control probe retries; avoid probes taking longer than kubernetes timeout settings

- os-eap-probes/1.0/added/livenessProbe.sh
- os-eap-probes/1.0/added/probe_common.sh
- os-eap-probes/1.0/added/readinessProbe.sh
- os-eap-probes/2.0/added/livenessProbe.sh
- os-eap-probes/2.0/added/probe_common.sh
- os-eap-probes/2.0/added/readinessProbe.sh
https://issues.jboss.org/browse/CLOUD-3246
No upstream issue, this change is only for the 7.2.x stable branches.
> [CLOUD-3246] - 7.2.x-openjdk11 - update ocp 4 probes for 7.2

- os-eap-migration/added/launch/openshift-migrate-common.sh
https://issues.jboss.org/browse/CLOUD-3333
> [CLOUD-3333] - os-eap-migration fails if installed EAP image has been patched

- os-eap-migration/added/launch/openshift-migrate-common.sh
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/130 https://github.com/jboss-container-images/jboss-eap-modules/pull/125
https://issues.jboss.org/browse/CLOUD-3348
https://issues.jboss.org/browse/CLOUD-3349
> [CLOUD-3349] - openshift-migrate.sh terminates with Max retries exceeded with url: /management

- os-eap7-openshift/added/standalone.conf
- tests/features/7/gc.feature
https://issues.jboss.org/browse/CLOUD-3270
> [CLOUD-3270] - There is no environment variable to configure the initial metaspace size

- jboss-eap-logging-ext/module.yaml
- os-eap-db-drivers/module.yaml
- os-eap-launch/module.yaml
- os-eap-logging/module.yaml
- os-eap-probes/module.yaml
- os-eap-txnrecovery/module.yaml
- os-eap64-modules/module.yaml
- os-eap64-ping/module.yaml
- os-eap64-sso/module.yaml
https://issues.jboss.org/browse/CLOUD-3377
No upstream PR, this is cekit-3.2.x build fixes for 6.4 only.
> [6.4.x] - CEKit 3.2.x build fixes for CPaaS

- os-eap-hawkular/added/standalone.conf
https://issues.jboss.org/browse/CLOUD-3412
No upstream issue, hawkular is not included in any JDK 11+ image.
> CLOUD-3412 - add deprecation notice for hawkular on EAP 7.2 OpenJDK 8

- os-eap-sso/added/keycloak.sh
https://issues.jboss.org/browse/CLOUD-3424
> CLOUD-3424 - invalid keytool path in openjdk11 images

- tests/examples/test-app-postgres/galleon/provisioning.xml
- tests/examples/test-app-prov-mysql-postgres/galleon/provisioning.xml
- tests/examples/test-app-prov-mysql/galleon/provisioning.xml
- tests/features/admin.feature
- tests/features/datasource.feature
- tests/features/driver.feature
- tests/features/galleon.feature
- tests/features/s2i.feature
- tests/features/security_domains.feature
- tests/features/sso.feature
Issue: https://issues.jboss.org/browse/CLOUD-3428
- Updated test projects to use datasources 1.0.5.CD.Alpha2
- Clean-up references to WIP branches tests projects.
> Fix for CLOUD-3428, Evolve behave feature tests to use latest drivers

- jboss/container/eap/galleon/build-settings/osbs/artifacts/settings.xml
- jboss/container/eap/galleon/module.yaml
- tests/features/galleon.feature
Issue: https://issues.jboss.org/browse/WFWIP-258
* osbs settings to use tmp galleon local cache
* Do not keep build artifacts
* Fixed test (finding, unrelated to issue).
> Fix for WFWIP-258,Galleon Maven repo in builder image contains additional artifacts

- jboss/container/eap/galleon/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/configs/standalone/model.xml
Issue: https://issues.jboss.org/browse/CLOUD-3432
Licenses files provisioned in all cases.
> Fix for CLOUD-3432, Licenses files should be provisioned along galleon layers

- os-eap7-openshift/module.yaml
https://issues.jboss.org/browse/JBEAP-18074
> JBEAP-18074 - Update OpenJ9 s390x build to use official RPMs from cct_module

- os-eap7-openshift/added/standalone.conf
The solution is a bit hacky, but I haven't found a better approach, so maybe this one is acceptable.
EAP in standalone.sh will avoid adding any GC log file configuration if there is any JAVA_OPTS setting related to GC logs. This check clashes with the jvm_specific_diagnostics for JDK 11, where the `-Xlog:gc::utctime` decorator is enabled.
To prevent EAP skips the GC log file configuration due to the jvm_specific_diagnostics settings, we could remove the settings from the JAVA_OPTS and add them to PREPEND_JAVA_OPTS. That change will bypass the EAP specific checks. 
jira issue: https://issues.redhat.com/browse/CLOUD-3452
> [CLOUD-3452] Move GC logs to PREPEND_JAVA_OPTS to bypass the specific EAP checks

- .gitignore
- jboss/container/eap/openshift/modules/added/modules/system/layers/openshift/io/narayana/openshift-recovery/main/module.xml
- jboss/container/eap/openshift/modules/configure.sh
- jboss/container/eap/openshift/modules/module.yaml
- os-eap-txnrecovery/bash/added/logging.properties
- os-eap-txnrecovery/bash/added/partitionPV.sh
- tests/features/tx-recovery.feature
https://issues.redhat.com/browse/CLOUD-3289
Adding a way to use non-postgresql and non-mysql JDBC drivers and configure the connection for the transaction recovery scaledown processing when JDBC object store is used.
This change, fixes and code additions and released jbosstm tools `.jars`, expects for user defining manually a module named as `io.narayana.openshift-recovery.jdbc` which is the place where JDBC driver jar files are stored and used by the recovery module `io.narayana.openshift-recovery` from.
The module may be created with galleon feature pack - e.g. I did it for oracle like this: https://github.com/ochaloup/wildfly-datasources-galleon-pack/commit/3d475603638016b6a21843f1832e148136ef9c71.
> [CLOUD-3289] adding optional module for transaction recovery jdbc driver

- os-eap7-openshift/module.yaml
The module name was changed here: https://github.com/jboss-openshift/cct_module/commit/ab8c07e3582004c4745810bbb3df58346b09c6e0
This blocks RH-SSO builds.
@luck3y can you please review?
> Fix old module ref

- os-eap-migration/added/launch/openshift-migrate-common.sh
Issue: https://issues.jboss.org/browse/CLOUD-3465
Use new way to configure the server from wildfly-cekit-modules
> Fix for CLOUD-3465, migration fails due to missing configure.sh file

- os-eap-migration/added/launch/openshift-migrate-common.sh
- os-eap-txnrecovery/bash/added/partitionPV.sh
Issue: https://issues.redhat.com/browse/CLOUD-3471
Signed-off-by: JF Denise jdenise@redhat.com
Configure the server only once prior to start migrations.
> Fix for CLOUD-3471, Can't run multiple server during migration

- tests/examples/test-app-postgres/galleon/provisioning.xml
- tests/examples/test-app-prov-mysql-postgres/galleon/provisioning.xml
- tests/examples/test-app-prov-mysql/galleon/provisioning.xml
Upgrade tests dependencies of wildfly-datasources FP. Required now that no more producers are present in the image.
> Upgrade tests to datasources 1.0.7.CD.Alpha1

- jboss/container/eap/launch/added/openshift-launch.sh
This PR follows up https://github.com/jboss-container-images/jboss-eap-modules/pull/178
It just keeps the $instanceDir variable inside of the double-quotes. `launchServer` expects only one argument, and keeping the variable inside could prevent a wrong argument interpretation if $instanceDir contains a blank space.
> Do not exclude instanceDir variable from double quoting

- os-eap7-openshift/added/standalone.conf
When java-default-options is sourced by any script to make use of its functions, by default prints to the standard output the calculated JAVA_OPTS
We cannot remove this echo, because it can be used by other parties to get the calculated values when sourcing it, so a workaround to avoid print this message when the server start could be to redirect to null the output when we are sourcing it in the standalone.conf file.
Jira issue: https://issues.jboss.org/browse/CLOUD-3444
> [CLOUD-3444] Redirect dynamic_resources.sh standard output to null when sourcing in standalone.conf

- jboss/container/eap/s2i/bash/README.adoc
- jboss/container/eap/s2i/bash/module.yaml
[CLOUD-3548] Update the name of the Maven S2I module to the cct_module's 0.41.0 form
Replace 'jboss.container.maven.s2i.bash' with 'jboss.container.maven.s2i'
as used in 0.41.0 tag of the cct_module. See:
https://github.com/jboss-openshift/cct_module/pull/372/files
for details
Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>
https://issues.redhat.com/browse/CLOUD-3548
> [CLOUD-3548] Update the name of the Maven S2I module to the cct_module's 0.41.0 form

- os-eap70-sso/configure.sh
- os-eap70-sso/module.yaml
Issue: https://issues.redhat.com/browse/CLOUD-3555
Handle the adapter part bundled in the default server.
> Fix for CLOUD-3555, Upgrade to RH-SSO 7.4 Image and adapter

- tests/features/datasource.feature
https://issues.redhat.com/browse/JBEAP-18660
https://issues.redhat.com/browse/CLOUD-3562
master PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/188
These are tests for update in wfly cekit modules of PR: https://github.com/wildfly/wildfly-cekit-modules/pull/176
> [CLOUD-3562][JBEAP-18124] adding tests for txn isolation being used for non-xa datasources

- jboss/container/eap/galleon/artifacts/opt/jboss/container/eap/galleon/patching.sh
- jboss/container/eap/galleon/config/ee/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/wildfly-user-feature-pack-build.xml
- jboss/container/eap/galleon/config/mp/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/wildfly-user-feature-pack-build.xml
- jboss/container/eap/galleon/module.yaml
Fix for: https://issues.redhat.com/browse/CLOUD-3651
This fix depends on : https://github.com/wildfly/wildfly-cekit-modules/pull/188
* Introduce new script that runs once the maven repository has been unzipped. The script patches the wildfly-user-feature-pack-build.xml with the set of patches present in the maven repository (if any).
> [EAP 7.3.x and XP 1.0] Fix for CLOUD-3650, Support patched image builder Maven repository

- jboss/container/eap/galleon/artifacts/opt/jboss/container/eap/galleon/patching.sh
- jboss/container/eap/galleon/module.yaml
Fix for: https://issues.redhat.com/browse/CLOUD-3651
This fix depends on : wildfly/wildfly-cekit-modules#188
This fix depends on : https://github.com/jboss-container-images/jboss-eap-7-image/pull/198
* Introduce new script that runs once the maven repository has been unzipped. The script patches the wildfly-user-feature-pack-build.xml with the set of patches present in the maven repository (if any).
> [MASTER] Fix for CLOUD-3650, Support patched image builder Maven repository

- os-eap7-openshift/added/standalone.conf
- tests/features/7/gc.feature
Backport changes to 7.2.x: 
Backported PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/138/files
Original Jira: https://issues.jboss.org/browse/CLOUD-3270
This patch will fix https://issues.jboss.org/browse/CLOUD-3392. 
It requires https://github.com/jboss-openshift/cct_module/pull/361
> CLOUD-3270 - There is no environment variable to configure the initial metaspace size

- jboss-eap-cd-openshift-modules/module.yaml
- os-eap64-modules/module.yaml
- os-eap71-modules/module.yaml
The txn-recovery-marker-jdbc build was deleted from Brew and cause
Freshmaker faill to rebuild images.
Another build was generated with the same version, but the metadata
f the artifacts have changed. The values should be fixed in the Openshift
code.
Signed-off-by: Daniel Kreling <dkreling@redhat.com>
> [CLOUD-3679] Update txn-recovery-marker-jdbc (narayana) md5 value

- jboss-eap-cd-openshift-modules/module.yaml
- os-eap64-modules/module.yaml
- os-eap71-modules/module.yaml
The txn-recovery-marker-jdbc build was deleted from Brew and cause Freshmaker faill to rebuild images.
Another build was generated with the same version, but the metadata of the artifacts have changed.
The values should be fixed in the Openshift code.
Signed-off-by: Daniel Kreling <dkreling@redhat.com>
> [CLOUD-3682] Update txn-recovery-marker-jdbc (narayana) md5 value

- jboss/container/eap/s2i/bash/README.adoc
- jboss/container/eap/s2i/bash/module.yaml
FYI, since we have 7.2 pinned to sprint-27, and it will never move off this branch, we need to revert this for now. 
We'll update the 7.3.x-legacy and master branches for new cct_modules instead.
Issue: https://issues.redhat.com/browse/CLOUD-3681
Signed-off-by: Daniel Kreling <dkreling@redhat.com>
> [CLOUD-3681] Revert CLOUD-3548

- jboss/container/eap/galleon/config/ee/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/configs/standalone/standalone.xml/config.xml
- tests/features/sso.feature
Issue: https://issues.redhat.com/browse/CLOUD-3771
> Fix for CLOUD-3771, Disable elytron security that core-tools layer brings to default config

- jboss/container/eap/galleon/config/ee/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/configs/standalone/standalone.xml/config.xml
- jboss/container/eap/galleon/eap73-compat/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/layers/standalone/datasources-web-server/layer-spec.xml
- jboss/container/eap/galleon/eap73-compat/configure.sh
- jboss/container/eap/galleon/eap73-compat/module.yaml
- tests/features/sso.feature
Issues:
https://issues.redhat.com/browse/CLOUD-3809
https://issues.redhat.com/browse/CLOUD-3771
Introduce new eap73-compact cekit module and reset management interface secured with elytron from default config.
> 7.3.4 and XP1.0.x galleon adjustments

- tests/features/basic.feature
- tests/features/jgroups.feature
Issue: https://issues.redhat.com/browse/JBEAP-20733
Upstream Issue: https://issues.redhat.com/browse/CLOUD-3509
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/184
> CLOUD-3509 correct misspelling of keystore

- tests/examples/test-app-ejb/pom.xml
- tests/examples/test-app-ejb/src/main/java/org/jboss/test/ejb/JAXRSConfig.java
- tests/examples/test-app-ejb/src/main/java/org/jboss/test/ejb/RestResource.java
- tests/examples/test-app-ejb/src/main/java/org/jboss/test/ejb/StatefulSessionBean.java
- tests/examples/test-app-ejb/src/main/webapp/WEB-INF/beans.xml
- tests/examples/test-app-jpa2lc/pom.xml
- tests/examples/test-app-jpa2lc/src/main/java/org/jboss/jpa2lc/DummyEntity.java
- tests/examples/test-app-jpa2lc/src/main/java/org/jboss/jpa2lc/JAXRSConfig.java
- tests/examples/test-app-jpa2lc/src/main/java/org/jboss/jpa2lc/RestResource.java
- tests/examples/test-app-jpa2lc/src/main/resources/META-INF/persistence.xml
- tests/examples/test-app-jpa2lc/src/main/webapp/WEB-INF/beans.xml
Add test applications necessary to verify jpa-dist and ejb-dist-cache Galleon layers.
We need to have the applications merged to later, in a second PR, add the behave test that test the Galleon layers
Jira issue: https://issues.redhat.com/browse/CLOUD-3470
Requires: wildfly/wildfly-cekit-modules#208
> [CLOUD-3470] Add ejb and jpa 2lc test applications

- jboss/container/eap/launch/added/launch/launch-config.sh
Issue: https://issues.redhat.com/browse/CLOUD-3918
Remove the scripts that are no more present in the image.
> Fix for CLOUD-3918, EAP 7.4.0.Beta OpenShift images, remove microprofile scripts

- jboss/container/eap/galleon/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/pom.xml
- jboss/container/eap/prometheus/config/module.yaml
- jboss/container/eap/prometheus/runtime/module.yaml
https://issues.redhat.com/browse/CLOUD-3918
Note this change reflects the corresponding change in cct_module v0.44.0 and is required to use cct_module moving forwards.
> CLOUD-3918 - EAP 7.4.0.Beta images

- tests/features/galleon.feature
- tests/features/mp-config.feature
- tests/features/tracing.feature
These tests can't pass with EAP 7.4.0, they should be removed and moved to XP3 tests. For now they are ignored.
> [EAP 7.4.0] [CLOUD-3949], ignore microprofile related tests

- jboss/container/eap/launch/added/openshift-launch.sh
Issue: https://issues.redhat.com/browse/CLOUD-3920
Related (cloned) issue: https://issues.redhat.com/browse/JBEAP-18005
Upstream PR: https://github.com/wildfly/wildfly-s2i/pull/147
> [CLOUD-3920] Add a timestamp at the beginning of image startup in EAP images

- jboss/container/eap/galleon/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/pom.xml
- jboss/container/eap/galleon/config/ee/artifacts/opt/jboss/container/eap/galleon/definitions/fat-default-server/provisioning.xml
- jboss/container/eap/galleon/config/ee/artifacts/opt/jboss/container/eap/galleon/definitions/slim-default-server/provisioning.xml
- jboss/container/eap/galleon/module.yaml
Until know we have used the WF major version internally for the s2i galleon fp.
https://issues.redhat.com/browse/CLOUD-3954
> [EAP 7.4.0][CLOUD-3954]Update versions to 23

- tests/features/galleon.feature
Add behave tests to verify jpa-dist and ejb-dist-cache Galleon layers
Jira issue: https://issues.redhat.com/browse/CLOUD-3470
Requires: https://github.com/jboss-container-images/jboss-eap-modules/pull/218
> [CLOUD-3470] Add behave tests for jpa-dist and ejb-dist-cache

- jboss/container/eap/final-setup/configure.sh
- jboss/container/eap/galleon/config/mp/artifacts/opt/jboss/container/eap/galleon/definitions/fat-default-server/provisioning.xml
- jboss/container/eap/galleon/config/mp/artifacts/opt/jboss/container/eap/galleon/definitions/slim-default-server/provisioning.xml
- jboss/container/eap/galleon/config/mp/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/pom.xml
- jboss/container/eap/galleon/config/mp/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/configs/standalone/model.xml
- jboss/container/eap/galleon/config/mp/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/configs/standalone/standalone-microprofile-ha.xml/config.xml
- jboss/container/eap/galleon/config/mp/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/packages/layers.conf/content/modules/layers.conf
- jboss/container/eap/galleon/config/mp/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/packages/layers.conf/package.xml
- jboss/container/eap/galleon/config/mp/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/packages/layers.conf/pm/wildfly/tasks.xml
- jboss/container/eap/galleon/config/mp/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/wildfly-user-feature-pack-build.xml
- jboss/container/eap/galleon/config/mp/configure.sh
- jboss/container/eap/galleon/config/mp/module.yaml
- tests/features/openshift.feature
https://issues.redhat.com/browse/CLOUD-3995
SIgned-off-by: Ken Wills <kwills@redhat.com>
> CLOUD-3995 - EAP XP 3.0

- jboss/container/eap/galleon/module.yaml
This reverts commit 7771f7eddff4c8ac5508e28e78f426170723260f.
S2I_FP_VERSION should be 23.0.0.Final, which is the Wildfly version that 7.4.0.GA was
based on.
> [JBEAP-22439] Revert "CLOUD-4005 - EAP XP 3.0 - Wrong S2I_FP_VERSION"

- tests/features/datasource-tx.feature
This PR addresses:
[CLOUD-4021](https://issues.redhat.com/browse/CLOUD-4021)
[EAPSUP-592](https://issues.redhat.com/browse/EAPSUP-592)
Requires changes in cekit moduels: [wildfly-cekit-modules#257](https://github.com/wildfly/wildfly-cekit-modules/pull/257)
PR cloned from #257 (please, close that PR before merging this one)
> [CLOUD-4021] dot is not permitted in tx datasource table name

- os-eap-activemq-rar/module.yaml
Note, MRRC is not available during builds, so artifacts like this need to come from brew. (This only appears to affect new build repos.)
> Update acivemq.rar to pull from brew, not MRRC

- os-eap-activemq-rar/module.yaml
Brew no longer supports md5 checksums, so fetch directly.
SIgned-off-by: Ken Wills <kwills@redhat.com>
> Update activemq.rar download location

- os-eap-probes/common/added/probes/probe/eap/dmr.py
Issue: https://issues.redhat.com/browse/CLOUD-3172
> [CLOUD-3172] readinessProve / livenessProbe fails with "'ascii' codec can't encode characters" when the locale supports non-ascii characters

- jboss/container/eap/tzdata-java/module.yaml
Issue: https://access.redhat.com/solutions/7025428
tzdata-java is not part of JDK 11.0.20
> Add module to install tzdata-java

- jboss/container/eap/galleon/config/ee-elytron/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/configs/standalone/standalone.xml/config.xml
- jboss/container/eap/galleon/config/ee-elytron/configure.sh
- jboss/container/eap/galleon/config/mp-elytron/artifacts/opt/jboss/container/eap/galleon/eap-s2i-galleon-pack/src/main/resources/configs/standalone/standalone-microprofile-ha.xml/config.xml
Issue: https://issues.redhat.com/browse/JBEAP-24017
The fix applies to both EAP 7.4.x and XP4 images.
> Fix for JBEAP-24017, [7.4.* JDK 17 images] - Missing required KEYCLOAK mechanism
